import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import { Toaster } from "react-hot-toast";
import { FormProvider } from "./context/form-context";
import { AuthProvider } from "./context/auth-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const navbarOptions = [
    { name: "About", linkHref: "about" },
    { name: "Pricing", linkHref: "pricing" },
  ];
  const loginOptions = [{ name: "Profile", linkHref: "profile" }];
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-amber-300`}
      >
        <AuthProvider>
          <FormProvider>
            <Toaster position="bottom-right" reverseOrder={false} />
            <Navbar
              brandName="Company"
              menuOptions={navbarOptions}
              loginOptions={loginOptions}
            />
            <div className="p-20"> {children}</div>
          </FormProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
